### ISSUE TITLE
Issue with converting scss to rtlcss in Angular component styles

### ISSUE THREAD

**Issue by MatasRut** [elchininet/postcss-rtlcss#120]
Hi, I have been trying to use the `postcss-rtlcss` plugin with `postcss-loader` in an Angular12 project.

All is well when styles are defined in the main styles.css file. However, the conversion does not work when styles are defined for a specific component. In such case Angular adds a `[_ngcontent-]` selector to each class of the component so it knows how the styles should be scoped. 

So sass input:
```
.padding-class {
  padding-left: 250px;
  p {
    color: blue;
    margin-left: 100px;
  }
}
```

Is converted like in the image below: 
![image](https://user-images.githubusercontent.com/78217506/151139760-96e76169-147d-4a8b-8363-d8b1c292391d.png)

As you can probably already see, the tag is also added after the generated `[dir]` selectors which causes the classes to not be applied.

Here is a simple project that reproduces the problem: https://github.com/MatasRut/rtlcss-example

Please advise on how this issue can be resolved.

**Comment by elchininet** [comment]
Hi @MatasRut,

Unfortunately, this doesn‘t fall in this plugin but in Angular, those scope classes are added later in the pipeline by Angular (it assumes that all the styles in a components belong to the component itself and not to the `:root` element). So, this plugin does this:

```css
[dir=ltr] .padding-class p {
    padding-left: 250px;
}

[dir=rtl] .padding-class p {
    padding-right: 250px;
}
```

And later Angular adds scopes to all elements in the selector, so this plugin doesn‘t have any control over that:

```css
[dir=ltr][angular-scope] .padding-class[angular-scope] p[angular-scope] {
    padding-left: 250px;
}

[dir=rtl][angular-scope] .padding-class[angular-scope] p[angular-scope] {
    padding-right: 250px;
}
```

You can find [the same issue](https://github.com/vkalinichev/postcss-rtl/issues/38) here, closed back in 2018 in the [postcss-rtl plugin](https://github.com/vkalinichev/postcss-rtl).

Regards.
