### ISSUE TITLE
Integrate better with CSS logical properties and values

### ISSUE THREAD

**Issue by xfq** [elchininet/postcss-rtlcss#151]
It would be great if this plugin works better with [CSS Logical Properties and Values](https://css-tricks.com/css-logical-properties-and-values/). I have two use cases.

First, I would like a mode to convert physical direction and dimension to logical ones (like converting `border-left` to `border-inline-start`).

Second, when there are logical and physical rules in the same rule, the semantics of the transformed rule could be wrong. For example:

```css
.test1, .test2 {
    padding-right: 20px;
    padding-inline-end: 30px;
}
```

is transformed to:

```css
.test1, .test2 {
    padding-inline-end: 30px;
}

[dir="ltr"] .test1, [dir="ltr"] .test2 {
    padding-right: 20px;
}

[dir="rtl"] .test1, [dir="rtl"] .test2 {
    padding-left: 20px;
}
```

But `padding-inline-end` should overwrite `padding-right` in LTR (or `padding-left` in RTL).

**Comment by elchininet** [comment]
Hi @xfq,

This plugin depends on [RTLCSS](https://rtlcss.com/) to manage the transformations, the work of this plugin is just to place in a single stylesheet the transformation that `RTLCSS` does. But [RTLCSS doesn‘t support logical properties](https://github.com/MohammadYounes/rtlcss/issues/138) (because these properties are already direction-dependant), so for that reason this plugin do not take them into account.

Try to revive the previous thread and check if @MohammadYounes still thinks that there are no plans to support logical properties.

But for the second issue that you are having maybe I can use one of the features of this plugin to see if I can cover it from here. I‘ll let this issue open and I will try to experiment a bit to see if I can bring a solution for you. I‘ll update you.

Regards.

**Comment by elchininet** [comment]
Hi @xfq,

Use [version 3.6.4 of the package](https://www.npmjs.com/package/postcss-rtlcss/v/3.6.4). In this version, logical declarations will not be overridden by physical ones because of specificity of the prefixed rules. This is the output of your example using this version of the package:

### Input

```css
.test1, .test2 {
    padding-right: 20px;
    padding-inline-end: 30px;
}
```

### Output

```css
[dir="ltr"] .test1, [dir="ltr"] .test2 {
    padding-right: 20px;
}

[dir="rtl"] .test1, [dir="rtl"] .test2 {
    padding-left: 20px;
}

[dir] .test1, [dir] .test2 {
    padding-inline-end: 30px;
}
```

Regards
