### ISSUE TITLE
With override mode turned on, some properties are still extracted

### ISSUE THREAD

**Issue by someBrown** [elchininet/postcss-rtlcss#216]
Here's the configuration from my project
```js
 plugins: [postcssRTLCSS({ mode: Mode.override })],
```
Following this configuration, I reproduced the output at the playground

```css
/* input */
.demo{
    background: linear-gradient(180deg, #fff27e 0%, #ffffff 100%);
    background-clip: text;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    color: rgba(255, 242, 126, 1);
}
```

```css
/* output*/
.demo{
    background: linear-gradient(180deg, #fff27e 0%, #ffffff 100%);
    -webkit-text-fill-color: transparent;
    color: rgba(255, 242, 126, 1);
}

[dir="rtl"] .demo{
    background: linear-gradient(-180deg, #fff27e 0%, #ffffff 100%);
}

[dir] .demo{
    background-clip: text;
    -webkit-background-clip: text;
}
```
**I don't know why background-clip was extracted.Is this a bug?** 

If I remove the backgound, the output meets my expectations

romove  **background: linear-gradient(180deg, #fff27e 0%, #ffffff 100%);**
```css
/* input and output are the same  */
.demo{
    background-clip: text;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    color: rgba(255, 242, 126, 1);
}
```

**Comment by elchininet** [comment]
Hi @someBrown,

That is expected, it has been implemented in that way intentionally. `background` is [a shortcut](https://developer.mozilla.org/en-US/docs/Web/CSS/background) for:

- background-attachment
- background-clip
- background-color
- background-image
- background-origin
- background-position
- background-repeat
- background-size

So, if you do this:

```css
.demo{
    background: linear-gradient(180deg, #fff27e 0%, #ffffff 100%);
    background-clip: text;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    color: rgba(255, 242, 126, 1);
}

[dir="rtl"] .demo{
    background: linear-gradient(-180deg, #fff27e 0%, #ffffff 100%);
}
```

In RTL mode, you will not have `background-clip` because it will be overriden by `background`.

To avoid this, the `background-clip` is moved to a rule with the same specificity of `[dir="xxx"]` and placed after it, so it doesn‘t matter what the value of `dir` is, it will be applied to both without being overriden in one of the directions.

You can check the [bothPrefix option](https://github.com/elchininet/postcss-rtlcss#bothprefix) in the documentation that explains this in detail.

**Comment by someBrown** [comment]
My knowledge of css has increased, thank you.

**Comment by elchininet** [comment]
>My knowledge of css has increased, thank you.

You are welcome. 👍

If you dont‘t want that behaviour, just avoid writing shorthands that could be flipped, together with the rules that they can override: e.g:  https://elchininet.github.io/postcss-rtlcss/#64bf6fde37709

Regards

**Comment by someBrown** [comment]
> > My knowledge of css has increased, thank you.
> 
> You are welcome. 👍
> 
> If you dont‘t want that behaviour, just avoid writing shorthands that could be flipped, together with the rules that they can override: e.g: https://elchininet.github.io/postcss-rtlcss/#64bf6fde37709
> 
> Regards

Hi，I rethought and read the source code today，I think the use of override mode should try not to affect the original style.Maybe it could look like 

```js
/* input */
.demo{
    background: linear-gradient(180deg, #fff27e 0%, #ffffff 100%);
    background-clip: text;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    color: rgba(255, 242, 126, 1);
}
```

```js
/* output*/
.demo{
    background: linear-gradient(180deg, #fff27e 0%, #ffffff 100%);
    background-clip: text;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    color: rgba(255, 242, 126, 1);
}

[dir="rtl"] .demo{
    background: linear-gradient(-180deg, #fff27e 0%, #ffffff 100%);
}

[dir] .demo{
    background-clip: text;
    -webkit-background-clip: text;
}
```
I think anyone using this model should be less concerned about bundle size.

In my scene，my project is a multiple entrances build, some of the old entrances rebuilds are affected by postcssRTLCSS, but the dir attribute is not added to the pages of these entrances.

Maybe I'm not using it in the right way, looking forward to your reply

**Comment by elchininet** [comment]
Hi @someBrown,

The override method (which is not an ideal method to manage left-to-right and right-to-left CSS) only exists because it generates less CSS, so it does not make sense to potentially make it bulkier than the combined method.

If you are trying to support pages with `dir` and without `dir` attribute at the same time and the bundle size is not a problem for you, you should use the [ltrPrefix, rtlPrefix](https://github.com/elchininet/postcss-rtlcss#ltrprefix-and-rtlprefix) and [bothPrefix](https://github.com/elchininet/postcss-rtlcss#bothprefix) options to generate dir-less selectors. Here you have an example (using the override mode, but you can use perfectly the combined one too):

### Options 

```javascript
plugins: [
    postcssRTLCSS({
        mode: Mode.override,
        ltrPrefix: 'html:not([dir])',
        bothPrefix: ['html:not([dir])', '[dir]']
    })
],
```

### Input 

```css
.demo {
    background: linear-gradient(180deg, #fff27e 0%, #ffffff 100%);
    background-clip: text;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    color: rgba(255, 242, 126, 1);
}
```

### Output

 ```css
.demo {
    background: linear-gradient(180deg, #fff27e 0%, #ffffff 100%);
    -webkit-text-fill-color: transparent;
    color: rgba(255, 242, 126, 1);
}

[dir="rtl"] .demo {
    background: linear-gradient(-180deg, #fff27e 0%, #ffffff 100%);
}

html:not([dir]) .demo, [dir] .demo {
    background-clip: text;
    -webkit-background-clip: text;
}
```
