### ISSUE TITLE
add ignoreList to options

### ISSUE THREAD

**Issue by alphaelf** [elchininet/postcss-rtlcss#218]
hi,
when we use postcss-rtlcss with other ui libraries like ant-design, we have not access to their css file to ignore what we want with directives e.g. with `/*rtl:ignore*/`  so it is good to have some option property to list all selectors we want to ignore:
```javascript
postcss: {
  plugins: {
     'postcss-rtlcss': {
         ignoreList: ['.ignore-rtl', '#ignore-me']
     }
  }
}```

**Comment by elchininet** [comment]
Hi @alphaelf,

That would bring multiple complexities that should be covered. What would be your expected output in these cases?

### Settings:
```
'postcss-rtlcss': {
    ignoreList: ['.ignore']
}
```

### Some random cases:
```css
.ignore, .do-not-ignore {
    left: 10px;
}
```

```css
.do-not-ignore:not(.ignore) {
    left: 10px;
}
```

```css
.do-not-ignore:has(~ .ignore) {
   left: 10px;
}
```

```css
:is(.ignore, .do-not-ignore) .child  {
   left: 10px;
}
```

Regards

**Comment by elchininet** [comment]
Hi @alphaelf,
I was trying to find proper solutions for your use case, but instead trying to manage all the complications that could bring ignoring a list of rules, I have created [another postcss plugin](https://github.com/elchininet/postcss-comments) to add comments to rules based on string or regular expression matchers. Just place that plugin before `postcss-rtlcss` adding directive comments to the rules that you want and it should work for your use case.

The plugin has been published just few minutes before, so if you find any issue using it, just let me know.

Regards

### Input

```css
.test1, .test2 {
    text-align: left;
}

.test-class {
    padding: 1px 2px 3px 4px;
}
```

```javascript
const result = postcss([
    postcssComments({
        rulesMatchers: [
            {
                 matcher: /^\.test-\w+$/,
                 prepend: 'rtl:ignore'
            }
         ]
    }),
    postcssRTLCSS()
]).process(cssInput);
```

### Output

```css
[dir="ltr"] .test1, [dir="ltr"] .test2 {
    text-align: left;
}

[dir="rtl"] .test1, [dir="rtl"] .test2 {
    text-align: right;
}

.test-class {
    padding: 1px 2px 3px 4px;
}
```
