### ISSUE TITLE
The plugin does not honour the stringMap directive.

### ISSUE THREAD

**Issue by 3baaady07** [elchininet/postcss-rtlcss#242]
As can be seen from the illustration, the string highlighted is the same after being processed, and the selector as well is not changed.
<img width="949" alt="image" src="https://github.com/elchininet/postcss-rtlcss/assets/18297214/5b20dcc5-4196-469d-92e8-4c8b9d1e3245">

before
```css
/* rtl:begin:options: {
  "stringMap":[ {
    "name"    : "prev-next",
    "search"  : "prev",
    "replace" : "next"
  } ]
} */
.carousel-control-prev-icon {
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23fff'%3e%3cpath d='M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z'/%3e%3c/svg%3e");
}

.carousel-control-next-icon {
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23fff'%3e%3cpath d='M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z'/%3e%3c/svg%3e");
}
/* rtl:end:options */
```

After
```css
/* rtl:begin:options: {
  "stringMap":[ {
    "name"    : "prev-next",
    "search"  : "prev",
    "replace" : "next"
  } ]
} */
.carousel-control-prev-icon {
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23fff'%3e%3cpath d='M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z'/%3e%3c/svg%3e");
}

.carousel-control-next-icon {
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23fff'%3e%3cpath d='M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z'/%3e%3c/svg%3e");
}
/* rtl:end:options */
```

**Comment by elchininet** [comment]
Hi @3baaady07,

`postcss-rtlcss` do not have `rtl:options` directives, [these are the directives supported by this plugin](https://github.com/elchininet/postcss-rtlcss?tab=readme-ov-file#control-directives). I think that you are getting that directive [from rtlcss](https://rtlcss.com/learn/usage-guide/control-directives/#Options) but that is only valid if you use `rtlcss` directly.

To use a `stringMap`, you need to use it through [an option](https://github.com/elchininet/postcss-rtlcss?tab=readme-ov-file#stringmap), and you will need to use also the [autoRename option](https://github.com/elchininet/postcss-rtlcss?tab=readme-ov-file#autorename) together to flip the selectors names (by default it is disabled).

Here you have a working example with your CSS code:

https://runkit.com/embed/wxaht3xnjabj

**Comment by 3baaady07** [comment]
For some reason, it's not working in my Vite project. Here's the code in `postcss.config.js`

```javascript
import postcssRTLCSS from 'postcss-rtlcss';
import { Autorename } from 'postcss-rtlcss/options';

export default {
   plugins: {
      autoprefixer: {},
      ['postcss-rtlcss']: postcssRTLCSS({
         autoRename: Autorename.strict,
         stringMap: [
            {
               name: 'prev-next',
               search: 'prev',
               replace: 'next'
            }
         ]
      })
   },
}
```

**Comment by 3baaady07** [comment]
Hi @elchininet,
> Is `postcss-rtlcss` working in your project and only that option is not working for you, or is `postcss-rtlcss` nor working at all? 

The plugin works as expected (prepending the html attribute `dir` to selectors with the appropriate values). The `stringMap`, however, does not have an effect even with the added `postcss` configuration.

> ...your only workaround for now would be doing [something like this](https://runkit.com/embed/apjvzeo15wsm), but I will try to...

The `SVG` values come from sass variables. Those variables are processed by the a third party sass function (Bootstrap - [`escape-svg`](https://github.com/twbs/bootstrap/blob/main/scss/_functions.scss#L131)) that has a specific case for `url()`. When adding the `rtl` directive with a `url` value, the function distorts the resultent value rendering faulty css.

I'll open an issue with Bootstrap about this but I have more faith in this plugin.. 😄

**Comment by elchininet** [comment]
Hi @3baaady07,

I would need a minimum reproducible example in a repo to debug it, otherwise it is very difficult to know what could be happening. Just make sure that those rules do not contain directional properties, `stringMap` will affect rules without directional properties, if the rule is processed in any way creating prefixed rules, `stringMap` will not do anything in them.

About adding the directives in SASS, just make sure that you are adding them [in this way](https://github.com/elchininet/postcss-rtlcss/issues/114#issuecomment-1008294135).

**Comment by 3baaady07** [comment]
Hi @elchininet,

I have added a basic [repo](https://github.com/3baaady07/postcss-rtlcss-test) that illustrates the issue. The detailed reproducible steps are described in the `README.md`.

Cheers, :)

**Comment by elchininet** [comment]
Hi @3baaady07,
Thanks for the repo, it is the best way to debug something.
What happens is that the `postcss.config.js` file is not using a valid configuration. I have consulted [the Vite documentation](https://vitejs.dev/guide/features#postcss) and the mention that the format of the config could be any supported format of [postcss-load-config](https://github.com/postcss/postcss-load-config?tab=readme-ov-file#postcssrcjs-or-postcssconfigjs). So, change your configuration to any of these ones and it will work:

### Plugins as an object

```typescript
import { Autorename } from 'postcss-rtlcss/options';

export default {
   plugins: {
      'postcss-rtlcss': {
         autoRename: Autorename.strict,
         stringMap: [
            {
               name: 'prev-next',
               search: 'prev',
               replace: 'next'
            }
         ]
      }
   }
}
```

### Plugins as an array

```typescript
import postcssRTLCSS from 'postcss-rtlcss';
import { Autorename } from 'postcss-rtlcss/options';

export default {
   plugins: [
      postcssRTLCSS({
         autoRename: Autorename.strict,
         stringMap: [
            {
               name: 'prev-next',
               search: 'prev',
               replace: 'next'
            }
         ]
      })
   ]
}
```

**Comment by elchininet** [comment]
Hi @3baaady07,

Check [this pull request](https://github.com/elchininet/postcss-rtlcss/pull/244), read the statement and let me know if it is clear and would solve your use case.

**Comment by 3baaady07** [comment]
hi @elchininet,

> ### Plugins as an object
> ```ts
> import { Autorename } from 'postcss-rtlcss/options';
> 
> export default {
>    plugins: {
>       'postcss-rtlcss': {
>          autoRename: Autorename.strict,
>          stringMap: [
>             {
>                name: 'prev-next',
>                search: 'prev',
>                replace: 'next'
>             }
>          ]
>       }
>    }
> }
> ```

That actually fixed it 👍
However, the desired result is to generate two different selectors prefixed with `[dir=***]` attribute which your recent pull request solves. My only concern is that I'm not too sure if I'm able to create bounds to the effect of `processRuleNames`.

For example:
```css
/* I want to change those */
.test2-right::before {
  content: "\f007";
}

.test2-left::before {
  content: "\f010";
}

/* ...but not those */
.hand-right {
  background-image: url("images/hand-right-[hash].png");
}

.hand-left{
  background-image: url("images/hand-left-[different hash].png");
}
```
Sorry if this sounds like a convoluted request.

**Comment by elchininet** [comment]
Hi @3baaady07,

You can use the [rtl:ignore directives](https://github.com/elchininet/postcss-rtlcss?tab=readme-ov-file#rtlignore-1) for that:

```css
/* I want to change those */
.test2-right::before {
  content: "\f007";
}

.test2-left::before {
  content: "\f010";
}

/* ...but not those */
/*rtl:begin:ignore*/
.hand-right {
  background-image: url("images/hand-right-[hash].png");
}

.hand-left{
  background-image: url("images/hand-left-[different hash].png");
}
/*rtl:end:ignore*/
```

But just in case that you want to ignore it in the whole file and just apply it to some rules, I have plans of creating a directive for that once the new version is released.

But remember that you can use what I recomended you [here](https://github.com/elchininet/postcss-rtlcss/issues/242#issuecomment-1871091113) with the current version of the library without setting any option:

https://www.sassmeister.com/gist/9a7c50edd00fa7ae68616b711816e8b5
