### ISSUE TITLE
Universal selector breaks raw directive

### ISSUE THREAD

**Issue by mgross1-godaddy** [elchininet/postcss-rtlcss#338]
minimal repro:
```css
/*rtl:raw:* { margin: 0;}*/
```
expected: 
```css
 [dir="rtl"] * { margin: 0;}
```
actual:
```css
/*rtl:raw:* { margin: 0;}*/
```

https://elchininet.github.io/postcss-rtlcss/#664e5db13ea64
