### ISSUE TITLE
property "background" is not working with hex color with opacity

### ISSUE THREAD

**Issue by jieweizheng** [elchininet/postcss-rtlcss#368]
input:
```css
.a {
    background: #00000080
}
```

expecting: 
```css
[dir="rtl"] .a {
    background: #00000080
}
```

but getting:
```css
[dir="rtl"] .a {
    background: #000000right 80 top 50%
}
```

result from playground:
<img width="1867" alt="image" src="https://github.com/user-attachments/assets/5a5dd9a9-283f-4856-b647-909eb2ca128d">

**Comment by elchininet** [comment]
Hi @jieweizheng,

Two things:

1. That rule should not be modified because it doesn't contain any declaration that should be flipped. So, the only way that you should expect that rule to be prefixed is if you use the `safeBothPrefix` option.

2. You should report your issue in [the RTLCSS repo](https://github.com/MohammadYounes/rtlcss) (which `postcss-rtlcss` uses behind the scenes). Insert that rule in [the playground](https://rtlcss.com/playground/) and check the result.

If you want to ignore that for now, just add an ignore directive before the rule:

```css
/*rtl:ignore*/
.a {
    background: #00000080;
}
```

Regards
