### ISSUE TITLE
Tailwind `translate` utility classes rtl support

### ISSUE THREAD

**Issue by ItaiYosephi** [elchininet/postcss-rtlcss#455]
Is there a way to make this plugin work work tailwind's translate utlity classes (i.e. `translate-x-1/2` )?

this is the class tailwind generates:
```
.-translate-x-1\/2 {
    --tw-translate-x: -50%;
    transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}
```

It would be nice if this plugin could generate this for rtl: 
```
[dir="rtl"] .-translate-x-1\/2 {
    --tw-translate-x: calc(-50% * -1);
}
```

**Comment by elchininet** [comment]
Hi @ItaiYosephi,
The work of `PostCSS RTLCSS` is to create prefixed rules in a single stylesheet, but the work of flipping the declarations falls on the scope of [RTLCSS](https://github.com/MohammadYounes/rtlcss), you should open the issue there.

The RTLCSS aliases [option](https://rtlcss.com/learn/usage-guide/options/) (which can be set also from this plugin) is to deal with CSS variables, it allows you to treat variables as properties, but I don't think that there is a CSS declaration that would be flipped in that way. Declarations as `background-position-x` will transform `30%` in `70%` but not in `-30%`.

As an alternative solution, some time ago [I created a postcss plugin](https://github.com/elchininet/postcss-comments) to prepend or append comments to rules, it allows one to deal with rules coming nor from the source code but from external libraries (it came out of [this request](https://github.com/elchininet/postcss-rtlcss/issues/218)). With this plugin it is possible to do something like this:

https://www.val.town/v/elchininet/savvyCoffeeFly

```javascript
import postcss from 'postcss';
import postcssRTLCSS from 'postcss-rtlcss';
import postcssComments from 'postcss-comments';

const input = `
.-translate-x-1\/2 {
  --tw-translate-x: -50%;
  transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}
`;

const raw = `rtl:raw:
.-translate-x-1\/2 {
  --tw-translate-x: 50%;
  transform: translate(var(--tw-translate-x));
}`;

const result = postcss([
    postcssComments({
      rulesMatchers: [
        {
          matcher: '.-translate-x-1\/2',
          prepend: 'rtl:freeze',
          append: raw
        }
      ],
    }),
    postcssRTLCSS()
]).process(input);

console.log(result.css);
```

It will generate this output:

```css
[dir="ltr"] .-translate-x-1/2 {
  --tw-translate-x: -50%;
  transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}

[dir="rtl"] .-translate-x-1/2 {
  --tw-translate-x: 50%;
  transform: translate(var(--tw-translate-x));
}
```

Regards
