### ISSUE TITLE
Is there a way to control the order of the ltr/rtl rules?

### ISSUE THREAD

**Issue by ItaiYosephi** [elchininet/postcss-rtlcss#458]
currently, the rtl rule always always comes last
```
[dir='ltr'] .test {
  margin-left: 10px;
}
[dir='rtl'] .test {
  margin-right 10px;
}
```

I would like to to flip it to this:

```
[dir='rtl'] .test {
  margin-right: 10px;
}
[dir='ltr'] .test {
  margin-left: 10px;
}

```

the use case, is that in `rtl`, some sections still need to be `ltr` (for example, code editors), and we add `dir="ltr"` to the surrounding div.  with rtl rule last, margin -right will always be applied...

**Comment by elchininet** [comment]
Hi @ItaiYosephi,

The `RTL` rule will be placed as the first one if you set [the source option](https://github.com/elchininet/postcss-rtlcss?tab=readme-ov-file#source) properly ([example](https://elchininet.github.io/postcss-rtlcss/#677d5dff67f72)). But that means that your source is in `RTL` and you want to generate an `LTR` counterpart (and that is not what you are intending to do), if you convert from `LTR` to `RTL` then the `LTR` rule will be always placed at first. 

For your use case (you want to override some `RTL` rules with an `LTR` version) you could use a workaround like [this one](https://github.com/elchininet/postcss-rtlcss/issues/414#issuecomment-2395575705).

**Comment by elchininet** [comment]
Hi @ItaiYosephi,
Let me know if you were able to set up the config to solve your issue, if not, I can help you to achieve it.
Regards

**Comment by elchininet** [comment]
Hi @ItaiYosephi,
Closing this one, if you still need support open another issue or a discussion.
Regards

**Comment by ItaiYosephi** [comment]
Hi @elchininet ,

Thanks for your response.
I was able to solve it like this:
```js
const config = {
  processKeyFrames: true,
  // not used, but for the sake of completeness
  bothPrefix: ':where(:dir(ltr), :dir(rtl))',
  ltrPrefix: ':where(:dir(ltr))',
  rtlPrefix: ':where(:dir(rtl))',
  prefixSelectorTransformer: (prefix, selector) => {
    // Check if the selector contains any pseudo-element
    for (const pseudo of pseudoElements) {
      if (selector.includes(pseudo)) {
        // Insert prefix before the pseudo-element
        return selector.replace(pseudo, `${prefix}${pseudo}`);
      }
    }

    // If no pseudo-element is found, append :dir(ltr)
    return `${selector}${prefix}`;
  },
};

const pseudoElements = [
  '::after',
  '::before',
  '::first-letter',
  '::first-line',
  '::backdrop',
  '::placeholder',
  '::marker',
  '::selection',
  '::cue',
  '::slotted',
  '::part',
  '::file-selector-button',
  ':after',
  ':before',
  ':first-letter',
  ':first-line',
];
```

this fixes my original issue, and also make `safeBothPrefix` not necessary, as the specifity of the selector doesn't increase due to `where`.

**Comment by elchininet** [comment]
>I was able to solve it like this:

Glad, that you solved it 👍

>this fixes my original issue, and also make safeBothPrefix not necessary, as the specificity of the selector doesn't increase due to where.

Just take into account that the `bothPrefix` is not only used if `safeBothPrefix` is enabled, it will also be used in other situations. For example, if a declaration could override a declaration in the original rule when moved after it, then the `bothPrefix` is used:

### input

```css
.test {
    background: linear-gradient(180deg, #fff27e 0%, #ffffff 100%);
    background-clip: text;
    color: red;
}
```

### output (using your custom `prefixSelectorTransformer`)

```css
.test {
    color: red;
}

.test:where(:dir(ltr)) {
    background: linear-gradient(180deg, #fff27e 0%, #ffffff 100%);
}

.test:where(:dir(rtl)) {
    background: linear-gradient(-180deg, #fff27e 0%, #ffffff 100%);
}

.test:where(:dir(ltr), :dir(rtl)) {
    background-clip: text;
}
```
