### ISSUE TITLE
Circumvent `@keyframes` at-rule mirroring output?

### ISSUE THREAD

**Issue by Volker-E** [elchininet/postcss-rtlcss#474]
Hi,
we're on version 5.6.0 of [postcss-rtlcss for our design system Codex here at Wikimedia](https://github.com/wikimedia/design-codex/blob/main/packages/codex/package.json#L78).

I've been wondering, and it might be just a configuration hiccup on my side, how to deal with keeping the same animation in both directionalities? The spinner animation should go clockwise (=should be the same) in both.

1. First try and assumed best idea on my side: The input `animation-name: cdx-animation-progress-indicator-spinner; /* rtl:ignore */` did **not** result in ouput of just one animation block.
2. Combining above with this input
```less
// Don't invert animation. Spinner should turn clockwise.
/* rtl:begin:ignore */
@keyframes cdx-animation-progress-indicator-spinner {
	0% {
		transform: @transform-progress-indicator-spinner-start;
	}

	100% {
		transform: @transform-progress-indicator-spinner-end;
	}
}
/* rtl:end:ignore */
```
did also mirror the animation and output it twice.

Output: 
```css
@keyframes cdx-animation-progress-indicator-spinner-ltr {
0% {
    transform: rotate(-45deg);
}
100% {
    transform: rotate(315deg);
}
}
@keyframes cdx-animation-progress-indicator-spinner-rtl {
0% {
    transform: rotate(-45deg);
}
100% {
    transform: rotate(-315deg);
}
}
``` 

The only way to have correct animation is to put `/* rtl:begin:ignore */` directive inside the keyframes, but again, we then have to accept duplicated output code (an `-ltr` and one `-rtl` keyframes at-rule, which I'd like to avoid.
