### ISSUE TITLE
overriding properties with "unset" gives unexpected results

### ISSUE THREAD

**Issue by y1n0** [elchininet/postcss-rtlcss#52]
Hello.
When override mode is enable, some properties like `border-left-width` do not convert correctly to RTL, since they get overridden with the "unset" keyword, which allows the default values to be used. In the case of `border-left-width`, setting it to `unset` results in a computed value of 3px in FF

```css
.cls {
  border-left-width: 1px;
}
```
gives: 
```css
.cls {
  border-left-width: 1px;
}

[dir="rtl"] .cls {
  border-left-width: unset; // this is 3px in Firefox
  border-right-width: 1px;
}

```

**Comment by elchininet** [comment]
Hello @y1n0,

That is what is expected by the override method, read the "Disadvantage of the override method" section in the [README](https://github.com/elchininet/postcss-rtlcss/blob/master/README.md). Because of that, the combined method is recommended.

If you want to fix it, you need to specify exactly the property that will be overridden:

```css
.cls {
    border-left-width: 1px;
    border-right-width: 0;
}
```

You will get:

```
.cls {
    border-left-width: 1px;
    border-right-width: 0;
}

[dir="rtl"] .cls {
    border-right-width: 1px;
    border-left-width: 0;
}
```
