### ISSUE TITLE
Tailwind v4 issue in dev env

### ISSUE THREAD

**Issue by laserhybiz** [elchininet/postcss-rtlcss#520]
When using tailwindcss with variants the generated css creates two css blocks but without the `dir` selectors (in dev only).

For example `sm:pl-8` will generate the following:

```css
@layer utilities {
  .sm\:pl-8 {
    @media (width >= 40rem) {
      padding-left: calc(var(--spacing) * 8);
    }
  }
}

@layer utilities {
  .sm\:pl-8 {
    @media (width >= 40rem) {
      padding-right: calc(var(--spacing) * 8);
    }
  }
}
```

**Comment by laserhybiz** [comment]
Reproduction repo: https://github.com/laserhybiz/rtlcss-bug-2

**Comment by elchininet** [comment]
Hi @laserhybiz,
Most probably it is related to [this](https://github.com/elchininet/postcss-rtlcss/issues/492).

**Comment by elchininet** [comment]
Hi @laserhybiz,
[It is reproducible in the playground](https://elchininet.github.io/postcss-rtlcss/#6823a683511ce). Most probably it is related to the at-rule in the middle of the rule and the declaration.

**Comment by laserhybiz** [comment]
I see in the playground that if you remove either `@layer` or `@media` it will work correctly

**Comment by elchininet** [comment]
>I see in the playground that if you remove either @layer or @media it will work correctly

Yes, that is right.

I think that the result should be the next one. Will something like this bring any issue?

```css
@layer utilities {
  [dir="ltr"] .sm\:pl-8 {
    @media (width >= 40rem) {
      padding-left: calc(var(--spacing) * 8);
    }
  }
  [dir="rtl"] .sm\:pl-8 {
    @media (width >= 40rem) {
      padding-right: calc(var(--spacing) * 8);
    }
  }
}
```
