### ISSUE TITLE
Flip variables values

### ISSUE THREAD

**Issue by fabercancio** [elchininet/postcss-rtlcss#65]
Check [this issue](https://github.com/vkalinichev/postcss-rtl/issues/56) in [postcss-rtl repo](https://github.com/vkalinichev/postcss-rtl).

The value of the variables is not flipped, for example:

```css
:root {
  --padding: 1rem 1rem 1.5rem 1.5rem;
}

.my-class {
  padding: var(--padding);
}
```

Is compiled to:

```css
:root {
  --padding: 1rem 1rem 1.5rem 1.5rem;
}

.my-class {
  padding: var(--padding);
}
```
