### ISSUE TITLE
Why delete clean option?

### ISSUE THREAD

**Issue by sunluyong** [elchininet/postcss-rtlcss#92]
I need to replace my source code, so the `ignore directives` need to be preserved

RTLCSS supports `clean` setting https://rtlcss.com/learn/usage-guide/options/

clean | boolean | true | Removes directives comments from output CSS.

**Comment by elchininet** [comment]
Hi @sunluyong,
Could you please, explain in more detail your issue? What do you mean with _I need to replace my source code_?
Regards

**Comment by sunluyong** [comment]
RTL support is necessary for our source code, so there are hand-writing RTL part in our source code, we just use rtlcss as eslint to fix rtl support we missed

**Comment by elchininet** [comment]
I would like to know why you are using this `postcss` plugin together with `RTLCSS`. These libraries should not be used together. `postcss-rtlcss` uses `RTLCSS` behind the scenes to create a single CSS file with both `ltr` and `rtl` rules at the same time, but `RTLCSS` flips all the rules to create a mirror of them with the intention of creating a separated CSS file.

Anyway, it would be interesting to hear what is your proposal. For example, taking the next CSS, what would be the expected result for you with a `clean` option set to `false`?

##### input

```css
.test1 {
    direction: ltr;
    margin: 0;
    background-color: #353639;
    font-family: "Droid Sans", sans-serif/*rtl:prepend:"Droid Arabic Kufi",*/;
    font-size: 16px/*rtl:14px*/;
    /*rtl:raw
    height: 50px;
    width: 100px;*/
}

.test2 {
    /*rtl:begin:source:rtl*/
    left: 10px;
    color: red;
    text-align: left;
    /*rtl:end:source*/
    /*rtl:rename*/
    background-image: url("/icons/icon-left.png");
    border: 1px solid gray;
}
```

##### current output removing the comments

```css
.test1 {
    margin: 0;
    background-color: #353639;
}

[dir="ltr"] .test1 {
    direction: ltr;
    font-family: "Droid Sans", sans-serif;
    font-size: 16px;
}

[dir="rtl"] .test1 {
    direction: rtl;
    font-family: "Droid Arabic Kufi","Droid Sans", sans-serif;
    font-size: 14px;
    height: 50px;
    width: 100px;
}

.test2 {
    color: red;
    border: 1px solid gray;
}

[dir="ltr"] .test2 {
    right: 10px;
    text-align: right;
    background-image: url("/icons/icon-left.png");
}

[dir="rtl"] .test2 {
    left: 10px;
    text-align: left;
    background-image: url("/icons/icon-right.png");
}
```
